export default {
  HBC_ADDRESS_PREFIX: [2, 16, 66],
  HBC_PATH: "m/44'/496'/0'/0/0",
  MESSAGE_FROM_PAGE: "page",
  MESSAGE_FROM_BACKGROUND: "background",
  MESSAGE_FROM_POPUP: "popup",
  METHOD_SIGN: "sign",
  METHOD_GET_ACCOUNT: "get_account",
  MEHTOD_CONNECT: "connect",
  METHOD_SET_STORE: "set_store",
  METHOD_GET_STORE: "get_store",
  METHOD_GET_BALANCE: "get_balance",
  METHOD_LOGIN: "login",
  METHOD_LOGOUT: "logout",
  METHOD_LOGGED_STATUS_QUERY: "logged_status_query",
};
